# ========================== {Seeds} ==========================

User.destroy_all
Product.destroy_all
Cart.destroy_all
CartItem.destroy_all



# ========================== {User} ==========================

User.create(username: "Ali", password_digest: "1234", admin: true)
User.create(username: "Jamalino", password_digest: "1234", admin: false)
User.create(username: "Jamackino", password_digest: "1234", admin: false)


# ========================== {Product} =======================


Product.create(name:"Dolce Gabbana",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 8770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Bravo Shirt",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 250, image:"http://cdna.tid.al/4df6e74fa4afcd760d42906bb7fcfd7618c0df31_600.jpg")
Product.create(name:"Max Made",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 120, image:"https://i.pinimg.com/originals/fc/e2/d9/fce2d9f1a9e35f694a095012506ff8b9.jpg")
Product.create(name:"Allo La Vie",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 320, image:"https://i.pinimg.com/originals/fc/e2/d9/fce2d9f1a9e35f694a095012506ff8b9.jpg")
Product.create(name:"Balenciaga", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 8970, image:"https://i.pinimg.com/originals/b2/b5/1d/b2b51d976b4fd407e29975e268334668.jpg")
Product.create(name:"Ultra Style",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 890, image:"https://i.pinimg.com/originals/07/ea/e5/07eae515f195bd3a491bf3145e7a6fa4.jpg")
Product.create(name:"Allo La Vie",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 320, image:"https://i.pinimg.com/originals/b8/fc/53/b8fc537a349562184781146bbc290ac1.jpg")
Product.create(name:"Handy Made",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 470, image:"https://i.pinimg.com/736x/5f/e1/04/5fe104837d5dafbe5fbf9081851b290d.jpg")
Product.create(name:"Fendi", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1300, image:"https://i.pinimg.com/originals/a8/2b/c2/a82bc25f0ef3f1856cf2eeadfacff00c.jpg")
Product.create(name:"Gravity Jeans",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 910, image:"https://i.pinimg.com/originals/56/07/eb/5607eb667df35e2ace510f36ba1b2c9e.jpg")
Product.create(name:"Alexander McQueen", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons.", price: 5670, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Gucci",description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Roger Vivier", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 9070, image:"http://www.machovibes.com/wp-content/uploads/2018/05/Simple-Everyday-Dressing-Ideas-for-Men-18.jpg")
Product.create(name:"Canali", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1250, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Louis Vuitton", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 2200, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Tom Ford", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1100, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Belstaff", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 6150, image:"https://i.pinimg.com/originals/b2/b5/1d/b2b51d976b4fd407e29975e268334668.jpg")
Product.create(name:"Saint Laurent", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1500, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Moncler", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1234, image:"https://i.pinimg.com/originals/a8/2b/c2/a82bc25f0ef3f1856cf2eeadfacff00c.jpg")
Product.create(name:"Kenzo", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 3100, image:"http://www.machovibes.com/wp-content/uploads/2018/05/Simple-Everyday-Dressing-Ideas-for-Men-18.jpg")
Product.create(name:"Balmain", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Dolce Gabbana",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 8770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Bravo Shirt",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 250, image:"http://cdna.tid.al/4df6e74fa4afcd760d42906bb7fcfd7618c0df31_600.jpg")
Product.create(name:"Max Made",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 120, image:"https://i.pinimg.com/originals/fc/e2/d9/fce2d9f1a9e35f694a095012506ff8b9.jpg")
Product.create(name:"Allo La Vie",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 320, image:"https://i.pinimg.com/originals/fc/e2/d9/fce2d9f1a9e35f694a095012506ff8b9.jpg")
Product.create(name:"Balenciaga", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 8970, image:"https://i.pinimg.com/originals/b2/b5/1d/b2b51d976b4fd407e29975e268334668.jpg")
Product.create(name:"Ultra Style",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 890, image:"https://i.pinimg.com/originals/07/ea/e5/07eae515f195bd3a491bf3145e7a6fa4.jpg")
Product.create(name:"Allo La Vie",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 320, image:"https://i.pinimg.com/originals/b8/fc/53/b8fc537a349562184781146bbc290ac1.jpg")
Product.create(name:"Handy Made",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 470, image:"https://i.pinimg.com/736x/5f/e1/04/5fe104837d5dafbe5fbf9081851b290d.jpg")
Product.create(name:"Fendi", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1300, image:"https://i.pinimg.com/originals/a8/2b/c2/a82bc25f0ef3f1856cf2eeadfacff00c.jpg")
Product.create(name:"Gravity Jeans",description: "In the mid-1980s, two aspiring Italian designers founded what would later become one of the country’s most recognizable luxury fashion houses. Seven years later, Dolce and Gabbana presented their first menswear collection and have been creating lust-worthy suits ever since." , price: 910, image:"https://i.pinimg.com/originals/56/07/eb/5607eb667df35e2ace510f36ba1b2c9e.jpg")
Product.create(name:"Alexander McQueen", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons.", price: 5670, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Gucci",description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Roger Vivier", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 9070, image:"http://www.machovibes.com/wp-content/uploads/2018/05/Simple-Everyday-Dressing-Ideas-for-Men-18.jpg")
Product.create(name:"Canali", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1250, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Louis Vuitton", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 2200, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Tom Ford", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1100, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Belstaff", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 6150, image:"https://i.pinimg.com/originals/b2/b5/1d/b2b51d976b4fd407e29975e268334668.jpg")
Product.create(name:"Saint Laurent", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1500, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")
Product.create(name:"Moncler", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1234, image:"https://i.pinimg.com/originals/a8/2b/c2/a82bc25f0ef3f1856cf2eeadfacff00c.jpg")
Product.create(name:"Kenzo", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 3100, image:"http://www.machovibes.com/wp-content/uploads/2018/05/Simple-Everyday-Dressing-Ideas-for-Men-18.jpg")
Product.create(name:"Balmain", description: "With a delightful blend of Japanese and French style, Kenzo is the best brand for men’s outerwear. With sleek designs and an Asian twist, you can enjoy colorful and one-of-a-kind pieces that will turn heads for the right reasons." , price: 1770, image:"http://iamgalla.com/wp-content/uploads/2015/01/DSC_5669-edit.jpg")




# ========================== {Cart} =========================








puts "Seeded Successfully "
